### ISSUE TITLE
Tech Prototype TODO List

### ISSUE THREAD

**Issue by 23nd** [Warped2713/mrprog#15]
# Tech Prototype

## Unacceptable Issues
- [x] Mod commands only work via DM in NormalMode? See #3 
- [x] MrProg @ mention catches more than intended. See issue #10
- [x] Not all cases for using name suffixes are handles, See issue #8
- [x] JSONFILE dependency was modified to add \r\n to JSON output. See Issue #14 
- [x] Temp files never get deleted. See Issue #14 
- [ ] Remove legacy code, see Issue #18
- [ ] Separate config data from process code (npc and enum still contain functions...), see Issue #11 
- [ ] No saving of data across d/c or shutdowns, see Issue #16
- [ ] Only works on one server per client instance, based on what is written in the config file. See #17
- [ ] Dependent on dev to keep bot running on local machine. See Issue #19
- [ ] GitBook documentation is outdated. See Issue #5 

## Main Features

- [x] Config file that lets you decide
    - [x] which server and channels should be used for Normal or Debug modes
    - [x] which roles should have which internal permissions (partnered, mod, or admin)
    - [x] what prefix to use for commands, such as ! or ?>
    - [x] what suffix to use (and enforce) on all partner names
    - [x] what word to use for partners (like NetNavi)
    - [x] what name to give the bot (like Mr. Prog)
- [x] Other required files that can be modified without touching actual code
    - [x] require/enum for designing personality dialogue, command names/permissions,    presets/variants
    - [x] require/npc for designing auto responding characters like Mr.Prog and NetOfficial
- [x] Run multiple versions of the bot in different shells, using different config files
- [x] Partners have a mood counter that changes each time they respond to the user (make lots of command errors and they slowly get upset with you-- unless you customize the dialogue to act differently)
- [x] Customize dialogue via JSON text file uploads or file URLs (max size 100KB)
- [x] Extended dialogue upload enabling custom phrase-response pairs, see #12  
- [x] Customize avatars via PNG or JPEG file uploads or URLs (max size 100KB)
- [x] Partner names support non-accented letters, numbers, and Japanese kana or kanji
- [ ] Mr.Prog initialization procedure: see #9 , also daily shop and battle info
- [ ] Database connection for saving data across servers (and across unexpected d/c or planned maintenance), see #16
- [ ] TBD

### General

- [x] Talk to Mr.Prog (find out how to create a partner, or get its current mood)
- [x] Get a list of all available preset-variant pairs
- [x] Get a summary of all variants for a given preset
- [x] Get detailed info about a specific preset-variant pair
- [x] Get a list of all commands available to your role in the current or specified channel
- [x] Get detailed info about a specific command
- [ ] TBD

### Partnered

- [x] Rename partner with alphanumeric, kana, or kanji
- [x] Recolor partner embed with hexadecimal color code
- [x] Download partner's custom dialogue or default dialogue (personality) file
- [x] Upload partner's custom dialogue file (mood modifier + responses for situations/mood)
- [x] Upload partner's avatar image (auto-scaled to 80px in largest dimension)
- [x] Reset all of the partner's customized data to default (WIP: resets everything, should have flags for specific fields to reset)
- [x] Get a summary of your partner's stats and system information (WIP: placeholders)
- [ ] Change navi preset/variants

### Mod/Admin

- [x] Shutdown the bot completely
- [x] Bulk delete messages from a channel
- [ ] Reset a specific user's partner to default values (with flags for which details to reset)
- [ ] Assign a TempBan role to partnered users who abuse the bot; these users won't be able to use the bot until this role is removed
- [ ] Add new presets and variants
- [ ] Edit presets and variants (and enable/disable)
- [ ] Edit guide data
- [ ] Edit config data such as command prefix, suffix, currency labels
- [ ] Edit server config data such as active channels, enableOC, and isDebugMode
- [ ] Edit command permissions
- [ ] Send Mr.Prog into the busy state, allowing only Mods/Admins to send commands (and only configuration commands) so that server settings can be changed without taking the bot offline.
