### ISSUE TITLE
Battle Prototype TODO List

### ISSUE THREAD

**Issue by 23nd** [Warped2713/mrprog#20]
# Battle Prototype

### General

- [ ] TBD

### Partnered Users

- [ ] @NetAlerts to get updates about the state of the Mr.Prog server (current status level, any challenges in progress, viruses to look out for, mystery data selection)
- [ ] Accept a request via mention (@ NetAlerts for crises, @ User for PvP)
- [ ] Decline a request via mention  (@ NetAlerts for crises, @ User for PvP)
- [ ] Challenge another user via mention
- [ ] Get info about a specific virus
- [ ] Get info about a specific item
- [ ] Move left/right/up/down in battle
- [ ] Use a battle chip in battle
- [ ] Execute a set of battle actions
- [ ] Bail out of a battle
- [ ] Reboot next day after losing a battle (or timing out / disconnecting!)
- [ ] TBD

### Mods/Admins

- [ ] Add new encounter data
- [ ] Edit encounter data
- [ ] Add new move/battlechip data
- [ ] Edit move/battlechip data
- [ ] TBD
